### ISSUE TITLE
x230 bios g2uj30us  v2.74 support

### ISSUE THREAD

**Issue by juhanoi** [hamishcoleman/thinkpad-ec#106]
is it safe to use this patch on x230 bios g2uj30us v2.74?
or should i rollback to v2.73 bios before applying patch?

**Comment by juhanoi** [comment]
nevermind i misunderstood how this works

**Comment by rad4day** [comment]
Even though you think you misunderstood, it's nice to see people actually asking questions instead of bluntly executing stuff which *could* break their devices :)

**Comment by hamishcoleman** [comment]
I just checked the EC version numbers in the latest 2.74 BIOS and - again - there has been no change in the EC firmware version, so this was a simple update to add
