### ISSUE TITLE
Lenovo newer model password break with patch file

### ISSUE THREAD

**Issue by azanwaqas** [hamishcoleman/thinkpad-ec#112]
Hi how are you every one any one can explain how make patch file for Lenovo password break just like T440S ETC PLZ explain method to reset TPM CERTIFICATE with flash bios modified

**Comment by hamishcoleman** [comment]
Sorry @azanwaqas, this repository does not have any BIOS patches or workarounds - just Embedded Controller patches.

You might have more luck looking through the forums (eg: https://forum.thinkpads.com/viewforum.php?f=68)
