### ISSUE TITLE
Is it possible to patch x220 bios to works with x230 keyboard?

### ISSUE THREAD

**Issue by ChipTechno** [hamishcoleman/thinkpad-ec#117]
Hello.
I swapped x230 and x220 keyboard. The x230 with patched bios can use x220 keyboard, but is there anyway to make x220 to works with x230 keyboard?
Thank in advance!

**Comment by hamishcoleman** [comment]
Unfortunately, the EC firmware in the x220 is based on a different chipset and has a different checksum system, so we cannot reprogram it.

However, all the keys on a keyboard installed in the x220 should generate keypress events - which means you should be able to use normal key remapper software to adjust things
(Unfortunately, not the Fn+key combo special keys)

**Comment by ChipTechno** [comment]
Thank you!
