### ISSUE TITLE
Thinkpad Edge E130 non genuine battery and not charging, any possibility to flash?

### ISSUE THREAD

**Issue by riadtaihi** [hamishcoleman/thinkpad-ec#118]
Dear guys,

Thank you for this nice space of sharing experiences and ideas.
I bought a second hand EDGE E130 with almost dead battery, and then bought a 6600 mah from Ebay, which shows as non Genuine and does not charge.

Is there any flash for the bios that can bypass it and make the battery work?

Thanks in advance.

Non genuine part number is: FRU P/N : 42T4957 (ASM P/N : 42T4958)

Thanks in advance!

**Comment by hamishcoleman** [comment]
Sorry, we dont know how to patch the E130 laptop

**Comment by leecher1337** [comment]
A patch is now available:

https://github.com/leecher1337/thinkpad-ec/tree/x131e
