### ISSUE TITLE
T430 BIOS 2.79

### ISSUE THREAD

**Issue by Erbsen-zaehler** [hamishcoleman/thinkpad-ec#122]
The flashing screen says 2.79 (G1ETB8WW) and cannot find the BIOS file if you have bios version 2.79 because 2.79 is actually G1ETB9WW. I got it to work by downgrading to 2.78 to make the name match G1ETB8WW and it could find the file. Flashing was successful though, must be a typo.

**Comment by hamishcoleman** [comment]
I'm not sure what was going on for you.  I had a look and found a typo in the text descriptions, but nothing that should have caused it not to find the bios file.

There is no difference in the EC generated for 2.79 and 2.78 - so there is no need for you to redo the EC patching, however, if you were able to take a screenshot of the error message that might show something to me
