### ISSUE TITLE
e330 battery whitelist problem

### ISSUE THREAD

**Issue by tarlabasi** [hamishcoleman/thinkpad-ec#123]
I have battery whitelist problem. 
I read support model information and I see e330 is same the l430 bios. but I didn't find l430 bios file. Can you help me?

**Comment by hamishcoleman** [comment]
Unfortunately, the e330 (and l430) is using different hardware to the types of laptops that this repository can currently patch.  I doubt that the e330 and l430 are using the same BIOS files either.

Sorry.

**Comment by leecher1337** [comment]
Can you try the Battery hotpatch that I created for this machine, in case you have a battery to try?
Thanks: https://github.com/leecher1337/thinkpad-Lx30-ec

**Comment by dartyukh-afk** [comment]
> Can you try the Battery hotpatch that I created for this machine, in case you have a battery to try? Thanks: https://github.com/leecher1337/thinkpad-Lx30-ec

Hi @leecher1337 , just checked your hotpatch with E330 - seems it works - not original battery starts to charge. So now the main question - how to make this permanent (to flash, not to patch).

**Comment by leecher1337** [comment]
@dartyukh-afk 
Just as with every other patch in this repo:
```
git clone https://github.com/hamishcoleman/thinkpad-ec.git
cd thinkpad-ec/
make patch_disable_keyboard clean
make patch_enable_battery clean
make patched.e330.img
```

**Comment by dartyukh-afk** [comment]
> [@dartyukh-afk](https://github.com/dartyukh-afk) Just as with every other patch in this repo:
> 
> ```
> git clone https://github.com/hamishcoleman/thinkpad-ec.git
> cd thinkpad-ec/
> make patch_disable_keyboard clean
> make patch_enable_battery clean
> make patched.e330.img
> ```

Yeah, already did this, thanks.
