### ISSUE TITLE
Is the T530 BIOS v2.75 (G4ETB5WW) supported?

### ISSUE THREAD

**Issue by ovunctukenmez** [hamishcoleman/thinkpad-ec#124]
Hello,
Could you tell if can I use this solution for the latest BIOS version 2.75 installed on my T530 please?
Thanks!

**Comment by hamishcoleman** [comment]
The T530 EC firmware version has not changed since BIOS 2.60, so you are fine to use this patch built from an earlier BIOS than 2.75
