### ISSUE TITLE
x230 BIOS unable to apply firmware update without genuine battery, safe to flash anyway?

### ISSUE THREAD

**Issue by yibitech** [hamishcoleman/thinkpad-ec#127]
When I try to update my BIOS from the official Lenovo firmware from version 2.64 to 2.75, I get prompted that it requires a fully charged battery. I'm sure others have had/will have similar problems as many of these units (mine included) are sold on eBay without hard drives or battery. I'm wondering if updating the bios before applying this is completely essential as doing so would require I purchase a genuine Lenovo battery which would negate the necessity of the BIOS flash. Thanks for all of your hard work keeping this amazing project going!

**Comment by hamishcoleman** [comment]
The EC firmware has not been updated since BIOS 2.61, so you are perfectly fine to use this patch without first updating your BIOS version.

Good luck!
