### ISSUE TITLE
Worked perfectly on my w530.

### ISSUE THREAD

**Issue by aravillest** [hamishcoleman/thinkpad-ec#139]
Used this for my w530. I wanted to use a t520 china battery and needed to flash the patch. Used ubuntu from USB1, used USB2 for making bootable patch usb. Has the Dual UEIF/LEGACY mode on with legacy as primary when flashing the patched bios. Took all SSD and HDD out before booting into ubuntu. 

**One thing to note, when applying the patch DO NOT FORGET TO make sure that the keyboard patch is off and only battery patch is on.** 

	
	make patch_disable_keyboard clean
	
	make patch_enable_battery clean

        make patched.w530.img 

I forgot to do this the first time and ended up only flashing keyboard ( which i did not need).
Had to go back and disable the keyboard and enable the battery. Worked out well after and keyboard went back to functional.

**Thank you very much for this patch.** Using it 3 years after the OP posted.

**Comment by hamishcoleman** [comment]
Thanks for the report.  Always good to here that thinks are working for people.
