### ISSUE TITLE
X230 EC Reset - Backlit keyboard stop working

### ISSUE THREAD

**Issue by kasik96** [hamishcoleman/thinkpad-ec#150]
I used classic keyboard on my X230 for some time, and i wanted to revert it and put back my X230 keyboard with backlight. I put my keyboard back and re-flashed EC with (make patch_disable_keyboard clean) parameter.

And everything is working fine again, except my backlight on keyboard. Light from the top of screen works [Fn] + [Space] but only it. It does not cycle. I am not sure if its problem of EC flash or Blowed FUSE (i dont know to test it). 

EDIT: I isolated pins when i was putting X220 Keyboard classic into X230

I hope i maked it clear to understand.  Thanks for any help :)

**Comment by mszumilak** [comment]
Try [Fn]+[Delete] then. If it works it means that you have installed image patched for classic 7-row keyboard (like in x220).

**Comment by kasik96** [comment]
Thanks for answer but thats not the problem. I can turn on light with [Fn] + [Space] but only that small light above the screen (thinklight), but my keyboard backlight does not work. I cannot start it with any shortcut. Just thinklight works not keyboard backlight. And it worked before.

**Comment by hamishcoleman** [comment]
Sorry, I dont have a lot of experience with putting the x230 keyboard back in.  However, it is clear that the EC can detect a non backlit keyboard and just skip that part of the backlight sequence. Since you isolated your x230 pins, there shouldnt be any blown fuses, but perhaps there is some other part of the backlight hardware that we dont understand.

**Comment by kasik96** [comment]
Thanks for reply. It would be nice if there would be anyone with experience putting back back-lit keyboard and succeeded. But until then, i am gonna use Classic keyboard again. Thanks for help.

**Comment by kasik96** [comment]
Problem solved, i am was thinking i had keyboard with backlight, but i installed wrong one apparently. So, i am sorry for this misunderstanding. EC flash works as it should. Thanks.

**Comment by hamishcoleman** [comment]
Aw, snap!  I guess that's a good answer - Thanks for letting us know.
