### ISSUE TITLE
Image is not bootable

### ISSUE THREAD

**Issue by taDachs** [hamishcoleman/thinkpad-ec#153]
I tried to create an image for my x230 but cant boot from it. The usb drive is fine, I managed to burn an Archlinux iso on it and boot from it. I tried both iso and img.

I also tried moving the file to windows and burn it with RUFUS, but it says it cant read the image or that it is missing a partition table.

**Comment by mszumilak** [comment]
Please make sure your bios is set to allow booting legacy devices (msdos partition table). If you allow only UEFI boot you won't be able to update your bios.

**Comment by taDachs** [comment]
Yes it it. The problem is I cant even create a bootable usb stick

**Comment by taDachs** [comment]
I managed to do it by using etcher as sudo
