### ISSUE TITLE
W530: not able to patch the latest BIOS/EC Version

### ISSUE THREAD

**Issue by HaydarB** [hamishcoleman/thinkpad-ec#157]
Hi, 

every time when I am trying to do the battery patch on my W530, the patch downloads the BIOS Version 2.75 and the EC Version 1.3 but not the latest Version 2.76 and 1.4.
My Laptop has the latest BIOS version installed so the patch doesn't work for me.
Any ideas what I can do?

Regards
Haydar

**Comment by mszumilak** [comment]
BIOS 2.76/EC 1.4 is not supported:
https://github.com/hamishcoleman/thinkpad-ec#compatibilty-warning

**Comment by HaydarB** [comment]
Thank you. 
I missunderstud that info, because the latest version is also listed in descriptiom.txt.
Regards
Haydar

**Comment by mszumilak** [comment]
@HaydarB please close the issue.
