### ISSUE TITLE
Goodbye to aftermarket x220t batteries on x230t laptop with BIOS 2.75 (GCETB5WW) with EC 1.15 (GCHT26WW)?

### ISSUE THREAD

**Issue by mokalovesoulmate** [hamishcoleman/thinkpad-ec#158]
As subject,

I stupidly updated everything after installing Windows 10 with Lenovo Vantage (Lenovo Vantage software also updated the BIOS even I know my battery were broken and planned to buy later)

Now I want to buy a x220t battery to be used on my x230t, then I arrived to this Github repository. I feel screwed up regarding the EC.

Is the genuine battery only the way to solve my x230t battery problem? (I havent make purchase to the x220t battery yet)

Thanks.

(currently sad, USD 220 wasted lol)

**Comment by mszumilak** [comment]
With 2.75 bios for x230t only the original battery is going to work. The other option is downgrading back to 2.73 and installing patched EC.

**Comment by mokalovesoulmate** [comment]
Wait, is it possible to downgrade BIOS from 2.75 to 2.73? That does include downgrading the EC?

**Comment by mszumilak** [comment]
Yes, I did similar downgrade for x230 (2.77 -> 2.75) and yes, it will downgrade the EC as it is integral part of the UEFI package.

**Comment by mokalovesoulmate** [comment]
Incredible, thanks. Will try

**Comment by mokalovesoulmate** [comment]
Wohoo!
I downgraded the BIOS, created the custom BIOS, flashed custom BIOS and EC, now I am confident to buy a new battery!
