### ISSUE TITLE
Can I update BIOS after patching?

### ISSUE THREAD

**Issue by catzybluphish** [hamishcoleman/thinkpad-ec#164]
I'd like to update my BIOS to 2.77 (X230). Is it safe after patching with an older BIOS version, or am I stuck with my current version? I've only used the battery whitelist patch.

**Comment by hamishcoleman** [comment]
If you upgrade the BIOS to 2.77, it will definitely automatically update the EC firmware, so you will lose your battery patch.

According to the release notes, the only change included in the 2.77 release is the one to add a signature to the EC - so you are not missing out on anything by not upgrading.
