### ISSUE TITLE
[HACK] How do I make this patch work on model B480

### ISSUE THREAD

**Issue by louisgv** [hamishcoleman/thinkpad-ec#17]
Hello, I'm so glad this project exist. Is there anyway I need to do to make it work on my B480? Just the battery patch would be awesome.

**Comment by hamishcoleman** [comment]
Sorry, the B480 is not a laptop from the Thinkpad line and uses incompatible firmware.

**Comment by louisgv** [comment]
Too bad :( Thank you for the reply!

**Comment by leecher1337** [comment]
Now supported with https://github.com/hamishcoleman/thinkpad-ec/pull/212
