### ISSUE TITLE
X230i jail break

### ISSUE THREAD

**Issue by ageryun** [hamishcoleman/thinkpad-ec#170]
I had below screen shot while I was in jail break of my thinkpad x230i.

![20200430_133839](https://user-images.githubusercontent.com/64578424/80682405-055fb380-8af5-11ea-9da0-69a373493a9f.jpg)

bios was downgraded to 2.60 from 2.77. but still has same 'unsupported' message.

**Comment by hamishcoleman** [comment]
Hi ageryun,
Are you reporting this issue to the right project?  Nothing on your screenshot looks like you are trying to patch your EC firmware.

**Comment by ageryun** [comment]
Hi, I was trying to jail break bios by using Ivyrain ISO image flashing. but not sure if that was done correctly. If here is not for this kind of question, then sorry I will delete that posting.

**Comment by hamishcoleman** [comment]
It is not so much that you shouldn't post it here - more that you will reach the right audience if you post an issue in the Ivyrain github

**Comment by ageryun** [comment]
Oops. Sorry. Thank you for letting me know. My first time to post on Github. Can you delete my issue..? I tried but couldn't.

**Comment by hamishcoleman** [comment]
No need to apologise.  Also, no need to delete the issue - anyone else who finds this will be able to see and follow the same advise :-)
