### ISSUE TITLE
Add wget to the command that installs the prerequisites 

### ISSUE THREAD

**Issue by zacchi4k** [hamishcoleman/thinkpad-ec#171]
Running this on WSL2, I was getting an error because wget was not installed, so I suggest adding wget to the command that installs the prerequisites

**Comment by hamishcoleman** [comment]
Thanks for pointing that out.  I have added wget.

Also, you will probably find other issues using WSL if you try to write the image to a USB stick

**Comment by zacchi4k** [comment]
> Thanks for pointing that out. I have added wget.
> 
> Also, you will probably find other issues using WSL if you try to write the image to a USB stick

For writing the images I just copy them over to the Windows folders (/mnt/driveletter/etc) and write them with Rufus or balenaEtcher

**Comment by hamishcoleman** [comment]
Good to know that it is that simple.  Thanks for testing!
