### ISSUE TITLE
Keyboard language

### ISSUE THREAD

**Issue by toniz4** [hamishcoleman/thinkpad-ec#180]
Does this patch for the x230 works for all languages? or just english?

**Comment by hamishcoleman** [comment]
Because we are simply adding some missing bits to the existing keyboard table, any international keyboards should work fine.

However, I have not personally tested that..

Which keyboard layout are you hoping to use?

**Comment by toniz4** [comment]
I hope to use a abnt2 Brazilian keyboard, but i'm worried there will be compatibility problems. And the original keyboard on the x230 is a abnt2 keyboard too. I think if a iso keyboard works, possibly a abnt2 keyboard would work too, since abnt2 is just a iso layout but with 'ç' and a '~' and accent button re positioned.

**Comment by hamishcoleman** [comment]
Ah, yes - this is just a ISO layout with a couple of different keycaps so you should be fine

**Comment by toniz4** [comment]
Thanks!
