### ISSUE TITLE
Any luck on the L530?

### ISSUE THREAD

**Issue by MauriceNorden** [hamishcoleman/thinkpad-ec#185]
Hello, 
Do you also have plans to make a patch for the lenovo L530?

Greetings,
Maurice

**Comment by MauriceNorden** [comment]
Nvm, didn't fully read the readme.md :-(

**Comment by snakeeater4526** [comment]
Did i miss something, i have a L530 and i will like to have the battery mod .
i know they said the patch is not compatible but is there any chance ?

Greetings
