### ISSUE TITLE
Fingerprint doesn't work anymore on X230

### ISSUE THREAD

**Issue by lars-lessing** [hamishcoleman/thinkpad-ec#190]
I have installed this on my x230. I deside to make the keyboard fit in the Palmrest and not to swap the Palmrest. After installing the patch I can't use the fingerprint reader anymore. The fingerprint manager ( Windows 7) says he have no fingerprint reader detected. It the Device manager I can see the reader. Same Problem under Windows 10.

**Comment by hamishcoleman** [comment]
The fingerprint reader is a USB device that is attached to the motherboard from the palmrest via the same cable as the touchpad.

Nothing in the keyboard physical changes or software changes should affect that.  So, I would check and re-seat the palmrest cables

**Comment by lars-lessing** [comment]
i have buy a new x220 palmrest with fingerprintreader and yet it worked. So i think my old fingerprint reader is defect.
