### ISSUE TITLE
T530 support?

### ISSUE THREAD

**Issue by ijustlovemath** [hamishcoleman/thinkpad-ec#2]
Just found this beautiful repo. Any plans to add T530 support?

**Comment by hamishcoleman** [comment]
Just had a look and the t530 firmware is identical to the w530 one - so that was a quick add.

I have added the patch file to the list on the thinkwiki: http://www.thinkwiki.org/wiki/Install_Classic_Keyboard_on_xx30_Series_ThinkPads#Steps_to_patch_your_Firmware
