### ISSUE TITLE
bios persists at an older version even after flashing (x230t)

### ISSUE THREAD

**Issue by leepton** [hamishcoleman/thinkpad-ec#245]
As the title says.

After flashing the bios with a thinkpad-ec patched x230t image (i selected the keyboard and battery patchsets), the system bios persists at my current version 2.75, while upon flashing the USB with ec it says that its downloading and patching 2.73.

I assume that for some reason my bios just refuses to get patched or somehow rolls back to its original version. 

Im booting the USB in legacy-only mode, and have boot rollback prevention disabled.

**Comment by hamishcoleman** [comment]
The x230t BIOS version 2.75 has digital signature protection - you will need to downgrade your BIOS before you can install any EC patches.

The message about downloading 2.73 that you can see is talking about the container that we are extracting the EC image from - it does not make any attempts to install or use the BIOS from that download.

**Comment by leepton** [comment]
I solved my problem by booting windows on my machine, and then running [ivyprep](https://github.com/n4ru/IVprep/blob/master/README.md) which can be used to succesfully downgrade the bios. Then i booted back into linux and proceeded with installing thinkpad-ec patches.

**Comment by hamishcoleman** [comment]
It is certainly possible to downgrade the BIOS using the lenovo provided ISOs - but I'm glad you found an answer that worked
