### ISSUE TITLE
Mod not working on T430

### ISSUE THREAD

**Issue by sebileis2017** [hamishcoleman/thinkpad-ec#37]
Hi there, I followed all of the instructions in the Readme, I updated my BIOS using the Lenovo software, and then booted into Linux and followed all the instructions. The EC mod appears to apply the update when I boot, and says the BIOS mod has been completed, but even after rebooting the machine, my keyboard is still mapped to the T430 keyboard functions. Any help would be greatly appreciated!

**Comment by hamishcoleman** [comment]
It does sound like you have done all the expected things already.

Can you share the contents of the "patched.t430.iso.report" file that was generated when you made the patched firmware?

**Comment by sebileis2017** [comment]
Sure thing. Here it is:
Buildinfo: v1-171-ga36764 (20170727) patched.t430.iso
Built: 2f49d711d520575ff9079d74c64ef495850a9818  t430.G1HT35WW.s01D2000.FL2

Patches applied:
t430.G1HT35WW.img.d/001_keysym.patch t430.G1HT35WW.img.d/002_dead_keys.patch
t430.G1HT35WW.img.d/003_keysym_replacements.patch
t430.G1HT35WW.img.d/004_fn_keys.patch t430.G1HT35WW.img.d/005_fn_key_swap.patch

Description: t430 BIOS 2.72 (G1ETB2WW) EC 1.13 (G1HT35WW)

**Comment by hamishcoleman** [comment]
Damn, that matches what I got building here exactly - so there is nothing wrong with your build (compared to mine)

I'm not sure what to suggest next, as we have clearly strayed into the grey area of exactly how Lenovo implemented the BIOS code

**Comment by sebileis2017** [comment]
Do you think that my version of the BIOS is so new that the mod doesn't want to work with it? My BIOS is dated January 31 2017 so it's fairly new,

**Comment by hamishcoleman** [comment]
That shouldnt be an issue - the patch is applied to a BIOS update from late Feb 2017, so that is newer

**Comment by sebileis2017** [comment]
Are there any other things that you think could be causing the issue? Or do I just have a stubborn machine? I have another T430 that I COULD try it on...

**Comment by hamishcoleman** [comment]
If you have tried while plugged into the power, with a charged battery and after switching UEFI boot on and off again, then you have tried all the tricks we have found.

I am a little surprised when issues like yours crop up.  Clearly, there are ways to make it work because there have been other people who didn’t experience issues - but we just dont know what the differences are.

Just to confirm - have you ever seen the screen after a reboot where it has a progress meter and then forces a second reboot?  This is the screen where it is actually flashing the EC firmware finally onto the EC chip.

**Comment by sebileis2017** [comment]
So tonight I tried out the modded BIOS on the other T430 in my possession, and it worked! Went the whole way through, went to the "flashing embedded controller - do not power off!" screen after it restarted, and then it worked! No idea why it won't work on the other T430, but I tried every trick in the book on that one. On the T430 where it wasn't working, I never saw the screen after reboot that you speak of. If you want, the non-working T430's type was 2349-AK1, while the one it did work on was type 2349-HV6....no clue what the difference is. If anything else happens I will be sure to make note of it.

**Comment by sebileis2017** [comment]
Update: Turns out the non-working T430 had a dead battery, and that's what was keeping the mod from installing. Man do I feel stupid. When I swapped in the battery from the working T430 it began flashing the BIOS as soon as I hit the power button! May this serve as a lesson to future modders, the importance of checking every variable!
