### ISSUE TITLE
Flashed wrong BIOS

### ISSUE THREAD

**Issue by gret08** [hamishcoleman/thinkpad-ec#42]
Hi I flashed the BIOS for the wrong model. I know that was a very stupid thing to do but I got our computers confused. I was wondering if there's a way to flash the original back so the computer will work again. I tried using the Insyde BIOS recovery but I'm not sure I did it correctly. 

Made a flash drive FAT and renamed the .fl1 file to BIOS.WPH. Held Fn and R and nothing ever happened. Please help if anyone knows how to fix this. Thank you. The computer is an X230 by the way.

**Comment by jeremyweston** [comment]
Hey, you should try making a new patched BIOS and applying that patch to the proper laptop ThinkPad model.
