### ISSUE TITLE
How to undo a T430 mod?

### ISSUE THREAD

**Issue by sebileis2017** [hamishcoleman/thinkpad-ec#53]
Hi there, I was wondering how I can undo the mod on a T430? I'm selling my T430 and was planning on putting the original keyboard back in, is it possible to undo the mod so the correct function keys for the T430 layout are recognized?

**Comment by hamishcoleman** [comment]
There sure is - you can build the firmware with all the patches disabled.

Have a read of https://github.com/hamishcoleman/thinkpad-ec/blob/master/docs/CONFIG.txt and see if that answers your question

**Comment by sebileis2017** [comment]
Do I build this firmware the same way I built the mod firmware in Linux?

**Comment by hamishcoleman** [comment]
Yes, it is the same firmware and build system, with some options changed to remove the patches

**Comment by sebileis2017** [comment]
Okay, thanks. I will give this a try tomorrow.

**Comment by sebileis2017** [comment]
I will comment here if it works or not.

**Comment by explit7** [comment]
I tryed on 2x Thinkpad T430. Keyboard mod is ok, but reverting doesn't work.
Did someone find the way to unapply patch?

**Comment by explit7** [comment]
This is very strange. I build new package without all patches at all (it says original Lenovo EC Package)
Tha package is flashed on the T430 but after restart the Thinklight is still on Fn+PgUp (Classic keyboard) and not FN+Space (Like it should be on new keyboard).

Alredy tried on 2x ThinkPad T430. Patch works. Reverting back doesn't work. Latest BIOS 2.74 + EC 1.13

**Comment by explit7** [comment]
can be closed. patching or undo patch requires battery and AC-Adapter connected!
