### ISSUE TITLE
W530 does not charge above some level

### ISSUE THREAD

**Issue by czikapu** [hamishcoleman/thinkpad-ec#54]
Hello :)
I applied your hack to my BIOS and I can succesfully boot to Windows, but my battery charges slower and slower and cannot get above like 75%.
I have battery with exceeded capacity.

**Comment by hamishcoleman** [comment]
Unfortunately, I have no idea why that would be happening.  The patch should not affect anything to do with charging (and if you didnt enable the battery validation patch then there is no changes at all to the battery system)
