### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Seraxis** [hamishcoleman/thinkpad-ec#58]
https://github.com/hamishcoleman/thinkpad-ec/blob/ceb0fe172879652bc3244754baca6751cb30aff2/README#L71

Is this not supposed to be "patched.x230.iso" rather than "...img"

**Comment by four0four** [comment]
No, because the iso is actually cdrom image (which does not boot when copied to a standard thumbdrive - ask me how I know...)

The generated .img files will boot properly.

**Comment by hamishcoleman** [comment]
@four0four is right - in those steps, this is definitely supposed to be using the .img to make a known bootable thumbdrive
