### ISSUE TITLE
./scripts/fix_mbr with syntax error

### ISSUE THREAD

**Issue by staeck64** [hamishcoleman/thinkpad-ec#63]
Hi,

while creating the patched version for my t430 i ran into problems with the make process.

_Your build has completed with the following details:

Buildinfo: v1-201-gceb0fe-dirty (20180123) patched.t430.img
Built: 649d8b45b94b4fe012f72e08c7de889250545dc0  t430.G1HT35WW.s01D2000.FL2

Patches applied:
t430.G1HT35WW.img.d/006_battery_validate.patch

Description: t430 BIOS 2.72 (G1ETB2WW) EC 1.13 (G1HT35WW)
./scripts/geteltorito -o patched.t430.img.tmp patched.t430.iso
Booting catalog starts at sector: 20 
Manufacturer of CD: NERO BURNING ROM
Image architecture: x86
Boot media type is: harddisk
El Torito image starts at sector 27 and has 75776 sector(s) of 512 Bytes

Image has been written to file "patched.t430.img.tmp".
./scripts/fix_mbr patched.t430.img.tmp
syntax error at ./scripts/fix_mbr line 94, near "..."
syntax error at ./scripts/fix_mbr line 97, near "..."
Execution of ./scripts/fix_mbr aborted due to compilation errors.
make: *** [patched.t430.img] Error 255_

In the script ./scripts/fix_mbr the lines  94 and 97 are somewhat strange.

# TODO - bit munge things
    if ($part->{start_cyl} > 0xff) {
        ...
    }
    if ($part->{end_cyl} > 0xff) {
        ...
    }

best regards

**Comment by hamishcoleman** [comment]
The error message you get should be more explanitory - the ``...`` is perl shortcut for indicating unimplemented code - you should get a message like ``Runtime error: Unimplemented at ./scripts/fix_mbr line 94``.

I have updated the code to not use those ``...`` - which should work around the syntax errors.  Can you tell me what the output of ``perl --version`` is?  The "unimplemented" operator was added with perl 5.12, which is over 7 years old now, so I am a little surprised.
