### ISSUE TITLE
Documentation unclear

### ISSUE THREAD

**Issue by staeck64** [hamishcoleman/thinkpad-ec#64]
Hi,

when cloning the thinkpad-ec repo the files in mec-tools are not downloaded. The files files have to be downloaded seperately.

Best Regards

Thomas

**Comment by rad4day** [comment]
or you could clone with the `--recursive` argument, as the mec-tools directory is part of a module.

**Comment by hamishcoleman** [comment]
When you build the firmware, it should automatically checkout the mec-tools.

Have you found that not to be the case?
