### ISSUE TITLE
Instruction wrong?

### ISSUE THREAD

**Issue by phandojo** [hamishcoleman/thinkpad-ec#65]
Says here that a T420 palmrest can be used: https://www.thinkwiki.org/wiki/Install_Classic_Keyboard_on_xx30_Series_ThinkPads#The_replacement_.28T430.29

But a video contradicting the info can be found here: https://www.youtube.com/watch?v=V74pSO8of4M

I am about to buy a 7-row keyboard for T430, but unsure if I should get anything else.

Thoughts?

Thanks in advance.

**Comment by explit7** [comment]
Palmrest from the T420 can't be used for T430. Only X220 palmrest instead X230 Palmrest.

You need to modify the t420 keyboard, so it can fit in T430.



On Saturday, 27 January 2018, phandojo wrote:
> Says here that a T420 palmrest can be used: https://www.thinkwiki.org/wiki/Install_Classic_Keyboard_on_xx30_Series_ThinkPads#The_replacement_.28T430.29
> 
> 
> But a video contradicting the info can be found here: https://www.youtube.com/watch?v=V74pSO8of4M
> 
> 
> 
> I am about to buy a 7-row keyboard for T430, but unsure if I should get anything else.
> 
> 
> Thoughts?
> 
> 
> 
> Thanks in advance.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/hamishcoleman/thinkpad-ec/issues/6

-- 
Kind regards / 
Mit freundlichen Grüßen

ExPLIT IT Solutions
Pawel Radomychelski

**Comment by hamishcoleman** [comment]
Thanks @explit7 - I've never had a t430 to try the mod on myself, so it is good to have confirmation.  I've updated that thinkwiki section with the details.

**Comment by phandojo** [comment]
@hamishcoleman I have T430 coming in and will use the 7-row keyboard

This guide have info on fixing the top portion of KB to prevent T430 chassis bulge, but not sure how accurate it is: http://www.instructables.com/id/ThinkPad-T430T430sX230-Classic-Keyboard-Mod/

**Comment by hamishcoleman** [comment]
@phandojo Unfortunately, I dont know how accurate that instructable is either - I've never actually had a T430 to try to mod.

The cutting off of the plastic nubs to stop the bulge sounds like it would work, but you should experiment
