### ISSUE TITLE
Want to flash but already have the new firmware (G7HT39WW)

### ISSUE THREAD

**Issue by paganda** [hamishcoleman/thinkpad-ec#72]
When trying to flash the EC with the .iso (modded or unmodded), I'm not prompted to flash the firmware, probably because it's already the newest. Is there a different way? I really want the classic keyboard mod.

**Comment by hamishcoleman** [comment]
The output from this build does not check the currently installed version, so your current version should not matter.

When you say that you are not prompted to flash the firmware, can you add more details?  I assume you have built a patched img file, written it to a usb stick and booted that?  what output do you see?

During your build, it should have finished with a section of text starting with "Your build has completed with the following details:" - can you paste that output here?

**Comment by rad4day** [comment]
Also even if everything succeeded, it will only flash the EC after the reboot if it's connected to a power outlet (at least this is how the T430s behaves).
