### ISSUE TITLE
Lenovo t440s invalid rfid error after flashing ec

### ISSUE THREAD

**Issue by Mafioso3** [hamishcoleman/thinkpad-ec#74]
Hi
Recently i got a lenovo t440s with svp bios password, i knew that password is encrypted into Ec MEC1633L.
I reflashed it with rt809h programmer, password was gone, but many error appear at startup, even after restoring original EC backup, errors remain. 
I know that's bios bad checksum.
I will apologize if someone could help me to fix this issue. 
Thanks in advance.

**Comment by hamishcoleman** [comment]
Sorry, I dont think I can help - I have no experience with any of the t440 laptops.

**Comment by laptop8fix** [comment]
i have same problem by flashing mec1633l with rt809h  ,rfid error appear any one have solution
