### ISSUE TITLE
x230 firmware update

### ISSUE THREAD

**Issue by blshkv** [hamishcoleman/thinkpad-ec#77]
There is a new firmware was released recently: g2uj28us.iso Version            2.72
Could you update it here as well?

Thank you!

**Comment by hamishcoleman** [comment]
They didnt update the EC version, so there is no changes to make.

However, that also makes it a simple patch - added 235fe8c3cd68e4caf869af2d15d58eff1328fa39

**Comment by blshkv** [comment]
you could use sha-256 as well, but it doesn't matter
```
SHA1:20b88f4e1a9f4330355dcfa461fff1fd74be544a
SHA-256:64b4251df9357b79da7391692d5ff9a146c6209508f8e4c1a3c124b33341fdfa
```

Cheers!

**Comment by hamishcoleman** [comment]
Yeah, I saw the sha-256 - and I know it is cryptographically better.

In this case, it is being used as one of many double-checks to ensure that we dont brick someone's laptop and I dont think that the extra bits help much.

That being said, if the config file format was not so simplistic, it might be more pleasant to use sha-256 checksums

**Comment by blshkv** [comment]
I have just flashed my laptop with the battery patch only. It worked! Thank you so much, you saved me! 
I purchased a battery online and it arrived yesterday but it wasn't detected as a genuine. Unfortunately, I  do not have time to change it as my trip is in 3 days. It is started charging after the patch. Hopefully, it won't explode in my hands.. Cheers!
