### ISSUE TITLE
Does any of the patches (for battery validation removal only) work on x131e?

### ISSUE THREAD

**Issue by biofaust** [hamishcoleman/thinkpad-ec#83]

**Comment by hamishcoleman** [comment]
Sorry, no.

I've just had a quick look at the x131e BIOS and that hardware is based on a different style of bios update files, so the existing infrastructure would need improvements to support handling these bios updates.  It is also an AMD cpu based laptop, so it is unlikely to have a EC firmware that is compatible with the current patches.

**Comment by biofaust** [comment]
My x131e is Intel CPU based (i3). But indeed I guess it is significantly
different from all other ECs still.

**Comment by hamishcoleman** [comment]
Ah, sorry - I must have misread some marketing about which CPU was in these systems.  Either way - when I downloaded the firmware updates, they didnt match any of the existing known patterns and I could not find the EC firmware embedded in the update to check if it was similar enough

**Comment by inbx** [comment]
So, is there any way to remove batteries whitelist on x131e?
Original bios update attached. TU
[g8uj31us.zip](https://github.com/hamishcoleman/thinkpad-ec/files/2333073/g8uj31us.zip)

**Comment by Kharabet** [comment]
Hi, @hamishcoleman
Is there any updates on x131e patch?

**Comment by hamishcoleman** [comment]
Sorry @Kharabet , the firmware for the x131e is structured differently than the systems which we are able to remove the battery check

**Comment by kocoman1** [comment]
can anyone update the descrptions.txt to say where the fl2 files for the ec file is in what iso for x131e? thx

**Comment by leecher1337** [comment]
Patch now available:
https://github.com/leecher1337/thinkpad-ec/tree/x131e
