### ISSUE TITLE
Removing whitelists? T430 T420 etc

### ISSUE THREAD

**Issue by buterrip69** [hamishcoleman/thinkpad-ec#85]
Hey guys, since this software is able to remove the battery verification and change the keys for the old keyboards, i'm guessing it would also be possible to remove the whitelist of the PCIe Half Mini Card ?
Is there a way to do this? Thanks
Thanks

**Comment by rad4day** [comment]
the whitelist is included in the bios. I don't know if it would be possible with this tool take a look at #70 and maybe you want to take a look at coreboot / libreboot as those replace the bios and therefore also the whitelist (but have several other complications)
