### ISSUE TITLE
Keyboard patch with normal keyboard?

### ISSUE THREAD

**Issue by laptopdude90** [hamishcoleman/thinkpad-ec#88]
I ordered a T520 battery for my T530 by mistake. As I understand it, they'll work together with the battery patch. However, since I'm flashing a custom BIOS anyway, I thought I might as well enable the keyboard patch. At some point in the future I intend to upgrade to a classic keyboard anyway. Will the factory installed keyboard still work with the keyboard patch enabled? Or should I disable that patch for now?

**Comment by hamishcoleman** [comment]
The factory installed keyboard will work for basic typing.  However, the keys that change between the two keyboards will be strange.  Basically, the insert/delete/home/end/pgup/pgdn/pgforward/pgback will all be a little jumbled.   That all being said, none of the keys are 'dead keys', so normal (non EC firmware) keyboard remapping tools will probably help you out for these keys.   However, the Fn+Fkey combos will not match the icons on the keys - and that is not something you can easily remap.
