### ISSUE TITLE
X230T - Patch ONLY the battery bypass?

### ISSUE THREAD

**Issue by KittoniuM** [hamishcoleman/thinkpad-ec#92]
Hi, how can I patch only the battery check?

I want to use the backlit modern keyboard I have right now.

**Comment by KittoniuM** [comment]
i assume i would have to add .OFF prefix to every file except the battery one?

**Comment by bakageta** [comment]
That's correct, you should have 006_battery_validate.patch, and every other patch should be renamed to patch.OFF.

**Comment by KittoniuM** [comment]
Thanks, already done it :)

________________________________

**Comment by ginto37** [comment]
Do we still have to do this or are the `make patch_disable_foo clean` steps all we need now?

**Comment by hamishcoleman** [comment]
These rename steps have been superseded by the `make patch_disable_foo clean` - you no longer need them
