### ISSUE TITLE
X220: any support to decrypt the original firmware?

### ISSUE THREAD

**Issue by jal2** [hamishcoleman/thinkpad-ec#96]
While docs/HACKING.txt mentions **make x220.8DHT34WW.img**, this fails with

_make: *** No rule to make target 'x220.8DHT34WW.img'.  Stop._

After adding a line

_+x220.8DHT34WW.img rule:IMG, ..._

to Descriptions.txt, the tool **mec-tools/mec_csum_flasher -c** fails with

_you should run this on the unencrypted image_

So I guess mec_encrypt -d currently fails for the X220?

**Comment by hamishcoleman** [comment]
Unfortunately, you are right.  The mec-tools pretty much only supports the **30 series - the **20 series uses a slightly different encryption system.

The line in the HACKING.txt should have read
  make x220.8DHT34WW.img.enc.orig
